<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_SLITS_SCATTER" Id="{088f7e26-c5bb-497a-8c53-88a89420dd05}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SLITS_SCATTER EXTENDS FB_SLITS
VAR_INPUT
END_VAR
VAR



END_VAR

   ]]></Declaration>
    <Implementation>
      <ST><![CDATA[

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>