<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_LIB" Id="{41f87cec-8d4f-488b-ae3e-a2c9e5843eec}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_LIB
VAR
    fbLIB_1: FB_MOTIONSTAGE;
    fbLIB_2: FB_MOTIONSTAGE;
    fbLIB_3: FB_MOTIONSTAGE;
    fbLIB_4: FB_MOTIONSTAGE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//fbLIB_1(
//	stMotionStage := Main.M3);
    
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>